name: powerpoint
description: Slides viewer and exporter
publish_to: "none"
version: 1.0.1+8

environment:
  sdk: ">=2.18.0-189.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_inappwebview: ^5.4.3+7
  mustache_template: ^2.0.0
  url_launcher: ^6.1.4
  file_utils:
    path: ../file_utils

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
